// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 12_02_move/src/libs/libserver/protobuf/proto_id.proto

#include "12_02_move/src/libs/libserver/protobuf/proto_id.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Proto {
}  // namespace Proto
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto = nullptr;
const uint32_t TableStruct_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n512_02_move/src/libs/libserver/protobuf"
  "/proto_id.proto\022\005Proto*\373\016\n\005MsgId\022\010\n\004None"
  "\020\000\022\025\n\021MI_NetworkConnect\020\001\022\027\n\023MI_NetworkC"
  "onnected\020\002\022\024\n\020MI_NetworkListen\020\003\022\027\n\023MI_N"
  "etworkListenKey\020\004\022\030\n\024MI_NetworkDisconnec"
  "t\020\n\022\032\n\026MI_NetworkDisconnectEx\020\013\022\037\n\033MI_Ne"
  "tworkRequestDisconnect\020\024\022\026\n\022MI_RemoveCom"
  "ponent\0202\022\026\n\022MI_CreateComponent\0203\022\023\n\017MI_C"
  "reateSystem\0204\022\013\n\007MI_Ping\020e\022\022\n\016MI_AppRegi"
  "ster\020f\022\022\n\016MI_AppInfoSync\020g\022\026\n\022MI_AppInfo"
  "ListSync\020h\022\025\n\020C2L_AccountCheck\020\350\007\022\027\n\022C2L"
  "_AccountCheckRs\020\351\007\022!\n\034MI_AccountQueryOnl"
  "ineToRedis\020\352\007\022#\n\036MI_AccountQueryOnlineTo"
  "RedisRs\020\353\007\022\031\n\024L2DB_QueryPlayerList\020\362\007\022\033\n"
  "\026L2DB_QueryPlayerListRs\020\363\007\022\023\n\016L2C_Player"
  "List\020\364\007\022\025\n\020C2L_CreatePlayer\020\366\007\022\027\n\022C2L_Cr"
  "eatePlayerRs\020\367\007\022\026\n\021L2DB_CreatePlayer\020\370\007\022"
  "\030\n\023L2DB_CreatePlayerRs\020\371\007\022\025\n\020C2L_SelectP"
  "layer\020\372\007\022\027\n\022C2L_SelectPlayerRs\020\373\007\022\031\n\024MI_"
  "LoginTokenToRedis\020\376\007\022\033\n\026MI_LoginTokenToR"
  "edisRs\020\377\007\022\022\n\rL2C_GameToken\020\200\010\022\025\n\020C2G_Log"
  "inByToken\020\314\010\022\027\n\022C2G_LoginByTokenRs\020\315\010\022\030\n"
  "\023MI_GameTokenToRedis\020\316\010\022\032\n\025MI_GameTokenT"
  "oRedisRs\020\317\010\022\025\n\020G2DB_QueryPlayer\020\320\010\022\027\n\022G2"
  "DB_QueryPlayerRs\020\321\010\022\023\n\016G2C_SyncPlayer\020\322\010"
  "\022\025\n\020G2M_RequestWorld\020\324\010\022\024\n\017G2S_CreateWor"
  "ld\020\325\010\022\020\n\013MI_Teleport\020\326\010\022\025\n\020MI_TeleportAf"
  "ter\020\327\010\022\023\n\016G2S_SyncPlayer\020\330\010\022\032\n\025G2S_Reque"
  "stSyncPlayer\020\331\010\022\024\n\017G2DB_SavePlayer\020\332\010\022\025\n"
  "\020G2S_RemovePlayer\020\333\010\022\023\n\016C2G_EnterWorld\020\334"
  "\010\022\023\n\016G2M_QueryWorld\020\335\010\022\025\n\020G2M_QueryWorld"
  "Rs\020\336\010\022\023\n\016S2C_EnterWorld\020\335\013\022\023\n\016S2G_SyncPl"
  "ayer\020\336\013\022\023\n\016S2C_RoleAppear\020\337\013\022\026\n\021S2C_Role"
  "DisAppear\020\340\013\022\r\n\010C2S_Move\020\341\013\022\r\n\010S2C_Move\020"
  "\342\013\022\034\n\027MI_BroadcastCreateWorld\020\321\017\022!\n\034MI_B"
  "roadcastCreateWorldProxy\020\322\017\022\031\n\024MI_WorldS"
  "yncToGather\020\271\027\022\036\n\031MI_WorldProxySyncToGat"
  "her\020\272\027\022 \n\033MI_AccountSyncOnlineToRedis\020\241\037"
  "\022\"\n\035MI_AccountDeleteOnlineToRedis\020\242\037\022\037\n\032"
  "MI_PlayerSyncOnlineToRedis\020\243\037\022!\n\034MI_Play"
  "erDeleteOnlineToRedis\020\244\037\022\026\n\021MI_RobotSync"
  "State\020\211\'\022\023\n\016MI_RobotCreate\020\212\'\022\021\n\014MI_Http"
  "Begin\020\220N\022\031\n\024MI_HttpInnerResponse\020\221N\022\026\n\021M"
  "I_HttpRequestBad\020\222N\022\030\n\023MI_HttpRequestLog"
  "in\020\223N\022\017\n\nMI_HttpEnd\020\203R\022\030\n\023MI_HttpOuterRe"
  "quest\020\204R\022\031\n\024MI_HttpOuterResponse\020\205R\022\022\n\014M"
  "I_CmdThread\020\241\234\001\022\017\n\tMI_CmdApp\020\242\234\001\022\026\n\020MI_C"
  "mdWorldProxy\020\243\234\001\022\021\n\013MI_CmdWorld\020\244\234\001\022\022\n\014M"
  "I_CmdCreate\020\245\234\001\022\026\n\020MI_CmdEfficiency\020\246\234\001\022"
  "\023\n\rMI_Efficiency\020\247\234\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto = {
    false, false, 1988, descriptor_table_protodef_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto,
    "12_02_move/src/libs/libserver/protobuf/proto_id.proto",
    &descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto::offsets,
    nullptr, file_level_enum_descriptors_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto,
    file_level_service_descriptors_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto_getter() {
  return &descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto(&descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto);
namespace Proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto);
  return file_level_enum_descriptors_12_5f02_5fmove_2fsrc_2flibs_2flibserver_2fprotobuf_2fproto_5fid_2eproto[0];
}
bool MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 10:
    case 11:
    case 20:
    case 50:
    case 51:
    case 52:
    case 101:
    case 102:
    case 103:
    case 104:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1010:
    case 1011:
    case 1012:
    case 1014:
    case 1015:
    case 1016:
    case 1017:
    case 1018:
    case 1019:
    case 1022:
    case 1023:
    case 1024:
    case 1100:
    case 1101:
    case 1102:
    case 1103:
    case 1104:
    case 1105:
    case 1106:
    case 1108:
    case 1109:
    case 1110:
    case 1111:
    case 1112:
    case 1113:
    case 1114:
    case 1115:
    case 1116:
    case 1117:
    case 1118:
    case 1501:
    case 1502:
    case 1503:
    case 1504:
    case 1505:
    case 1506:
    case 2001:
    case 2002:
    case 3001:
    case 3002:
    case 4001:
    case 4002:
    case 4003:
    case 4004:
    case 5001:
    case 5002:
    case 10000:
    case 10001:
    case 10002:
    case 10003:
    case 10499:
    case 10500:
    case 10501:
    case 20001:
    case 20002:
    case 20003:
    case 20004:
    case 20005:
    case 20006:
    case 20007:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
